apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: listener
  name: listener
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: listener
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: listener
    spec:
      containers:
        - args:
            - sh
            - -c
            - sleep 10 && python -u main.py
          image: jovasquez/listener
          name: listener
          resources: {}
      restartPolicy: Always
status: {}
